package com.soap.producer;

import javax.xml.ws.Endpoint;

import com.service.impl.CalculatorServiceImpl;

public class ProducerMain {

	public static void main(String[] args) {
		
		String url="http://localhost:1000/calci";
		Endpoint.publish(url, new CalculatorServiceImpl());
		System.out.println("Your service is publised at -> '"+url+"?wsdl'");
		System.out.println("Open any web browser with above URL to see the wsdl service generated by your Calculator");

	}

}
